/*INSERT INTO countries VALUES
    (DEFAULT, 'afganistan'),
    (DEFAULT, 'albania'),
    (DEFAULT, 'alemania'),
    (DEFAULT, 'andorra'),
    (DEFAULT, 'angola'),
    (DEFAULT, 'antigua y barbuda'),
    (DEFAULT, 'arabia saudita'),
    (DEFAULT, 'argelia'),
    (DEFAULT, 'argentina'),
    (DEFAULT, 'armenia'),
    (DEFAULT, 'australia'),
    (DEFAULT, 'austria'),
    (DEFAULT, 'azerbaiyan'),
    (DEFAULT, 'bahamas'),
    (DEFAULT, 'banglades'),
    (DEFAULT, 'barbados'),
    (DEFAULT, 'barein'),
    (DEFAULT, 'belgica'),
    (DEFAULT, 'belice'),
    (DEFAULT, 'benin'),
    (DEFAULT, 'bielorrusia'),
    (DEFAULT, 'birmania'),
    (DEFAULT, 'bolivia'),
    (DEFAULT, 'bosnia herzegovina'),
    (DEFAULT, 'botsuana'),
    (DEFAULT, 'brasil'),
    (DEFAULT, 'brunei'),
    (DEFAULT, 'bulgaria'),
    (DEFAULT, 'burkina faso'),
    (DEFAULT, 'burundi'),
    (DEFAULT, 'butan'),
    (DEFAULT, 'cabo verde'),
    (DEFAULT, 'camboya'),
    (DEFAULT, 'camerun'),
    (DEFAULT, 'canada'),
    (DEFAULT, 'catar'),
    (DEFAULT, 'republica centroafricana'),
    (DEFAULT, 'chad'),
    (DEFAULT, 'republica checa'),
    (DEFAULT, 'chile'),
    (DEFAULT, 'china'),
    (DEFAULT, 'chipre'),
    (DEFAULT, 'colombia'),
    (DEFAULT, 'comoras'),
    (DEFAULT, 'congo'),
    (DEFAULT, 'republica democratica del congo'),
    (DEFAULT, 'corea del norte'),
    (DEFAULT, 'corea del sur'),
    (DEFAULT, 'costa de marfil'),
    (DEFAULT, 'costa rica'),
    (DEFAULT, 'croacia'),
    (DEFAULT, 'cuba'),
    (DEFAULT, 'dinamarca'),
    (DEFAULT, 'dominica'),
    (DEFAULT, 'republica dominicana'),
    (DEFAULT, 'ecuador'),
    (DEFAULT, 'egipto'),
    (DEFAULT, 'el salvador'),
    (DEFAULT, 'emiratos arabes unidos'),
    (DEFAULT, 'eritrea'),
    (DEFAULT, 'eslovaquia'),
    (DEFAULT, 'eslovenia'),
    (DEFAULT, 'espana'),
    (DEFAULT, 'estados unidos'),
    (DEFAULT, 'estonia'),
    (DEFAULT, 'etiopia'),
    (DEFAULT, 'filipinas'),
    (DEFAULT, 'finlandia'),
    (DEFAULT, 'fiyi'),
    (DEFAULT, 'francia'),
    (DEFAULT, 'gabon'),
    (DEFAULT, 'gambia'),
    (DEFAULT, 'georgia'),
    (DEFAULT, 'ghana'),
    (DEFAULT, 'granada'),
    (DEFAULT, 'grecia'),
    (DEFAULT, 'guatemala'),
    (DEFAULT, 'guinea'),
    (DEFAULT, 'guinea bisau'),
    (DEFAULT, 'guinea ecuatorial'),
    (DEFAULT, 'guyana'),
    (DEFAULT, 'haiti'),
    (DEFAULT, 'honduras'),
    (DEFAULT, 'hungria'),
    (DEFAULT, 'india'),
    (DEFAULT, 'indonesia'),
    (DEFAULT, 'irak'),
    (DEFAULT, 'iran'),
    (DEFAULT, 'irlanda'),
    (DEFAULT, 'islandia'),
    (DEFAULT, 'israel'),
    (DEFAULT, 'italia'),
    (DEFAULT, 'jamaica'),
    (DEFAULT, 'japon'),
    (DEFAULT, 'jordania'),
    (DEFAULT, 'kazajistan'),
    (DEFAULT, 'kenia'),
    (DEFAULT, 'kirguistan'),
    (DEFAULT, 'kiribati'),
    (DEFAULT, 'kuwait'),
    (DEFAULT, 'laos'),
    (DEFAULT, 'lesoto'),
    (DEFAULT, 'letonia'),
    (DEFAULT, 'libano'),
    (DEFAULT, 'liberia'),
    (DEFAULT, 'libia'),
    (DEFAULT, 'liechtenstein'),
    (DEFAULT, 'lituania'),
    (DEFAULT, 'luxemburgo'),
    (DEFAULT, 'macedonia del norte'),
    (DEFAULT, 'madagascar'),
    (DEFAULT, 'malasia'),
    (DEFAULT, 'malaui'),
    (DEFAULT, 'maldivas'),
    (DEFAULT, 'mali'),
    (DEFAULT, 'malta'),
    (DEFAULT, 'marruecos'),
    (DEFAULT, 'islas marshall'),
    (DEFAULT, 'mauricio'),
    (DEFAULT, 'mauritania'),
    (DEFAULT, 'mexico'),
    (DEFAULT, 'micronesia'),
    (DEFAULT, 'moldavia'),
    (DEFAULT, 'monaco'),
    (DEFAULT, 'mongolia'),
    (DEFAULT, 'montenegro'),
    (DEFAULT, 'mozambique'),
    (DEFAULT, 'namibia'),
    (DEFAULT, 'nauru'),
    (DEFAULT, 'nepal'),
    (DEFAULT, 'nicaragua'),
    (DEFAULT, 'niger'),
    (DEFAULT, 'nigeria'),
    (DEFAULT, 'noruega'),
    (DEFAULT, 'nueva zelanda'),
    (DEFAULT, 'oman'),
    (DEFAULT, 'paises bajos'),
    (DEFAULT, 'pakistan'),
    (DEFAULT, 'palaos'),
    (DEFAULT, 'palestina'),
    (DEFAULT, 'panama'),
    (DEFAULT, 'papua nueva guinea'),
    (DEFAULT, 'paraguay'),
    (DEFAULT, 'peru'),
    (DEFAULT, 'polonia'),
    (DEFAULT, 'portugal'),
    (DEFAULT, 'reino unido'),
    (DEFAULT, 'ruanda'),
    (DEFAULT, 'rumania'),
    (DEFAULT, 'rusia'),
    (DEFAULT, 'islas salomon'),
    (DEFAULT, 'samoa'),
    (DEFAULT, 'san cristobal y nieves'),
    (DEFAULT, 'san marino'),
    (DEFAULT, 'san vicente y las granadinas'),
    (DEFAULT, 'santa lucia'),
    (DEFAULT, 'santo tome y principe'),
    (DEFAULT, 'senegal'),
    (DEFAULT, 'serbia'),
    (DEFAULT, 'seychelles'),
    (DEFAULT, 'sierra leona'),
    (DEFAULT, 'singapur'),
    (DEFAULT, 'siria'),
    (DEFAULT, 'somalia'),
    (DEFAULT, 'sri lanka'),
    (DEFAULT, 'esuatini'),
    (DEFAULT, 'sudafrica'),
    (DEFAULT, 'sudan'),
    (DEFAULT, 'sudan del sur'),
    (DEFAULT, 'suecia'),
    (DEFAULT, 'suiza'),
    (DEFAULT, 'surinam'),
    (DEFAULT, 'tailandia'),
    (DEFAULT, 'tanzania'),
    (DEFAULT, 'tayikistan'),
    (DEFAULT, 'timor oriental'),
    (DEFAULT, 'togo'),
    (DEFAULT, 'tonga'),
    (DEFAULT, 'trinidad y tobago'),
    (DEFAULT, 'tunez'),
    (DEFAULT, 'turkmenistan'),
    (DEFAULT, 'turquia'),
    (DEFAULT, 'tuvalu'),
    (DEFAULT, 'ucrania'),
    (DEFAULT, 'uganda'),
    (DEFAULT, 'uruguay'),
    (DEFAULT, 'uzbekistan'),
    (DEFAULT, 'vanuatu'),
    (DEFAULT, 'ciudad del vaticano'),
    (DEFAULT, 'venezuela'),
    (DEFAULT, 'vietnam'),
    (DEFAULT, 'yemen'),
    (DEFAULT, 'yibuti'),
    (DEFAULT, 'zambia'),
    (DEFAULT, 'zimbabue'),
    (DEFAULT, 'aruba'),
    (DEFAULT, 'islas cook'),
    (DEFAULT, 'curazao'),
    (DEFAULT, 'groenlandia'),
    (DEFAULT, 'islas feroe'),
    (DEFAULT, 'islas marianas del norte'),
    (DEFAULT, 'niue'),
    (DEFAULT, 'puerto rico'),
    (DEFAULT, 'san martin'),
    (DEFAULT, 'sahara occidental'),
    (DEFAULT, 'anguila'),
    (DEFAULT, 'bermudas'),
    (DEFAULT, 'islas caiman'),
    (DEFAULT, 'gibraltar'),
    (DEFAULT, 'guam'),
    (DEFAULT, 'montserrat'),
    (DEFAULT, 'nueva caledonia'),
    (DEFAULT, 'islas pitcairn'),
    (DEFAULT, 'polinesia francesa'),
    (DEFAULT, 'samoa americana'),
    (DEFAULT, 'santa elena ascension y tristan de acuna'),
    (DEFAULT, 'tokelau'),
    (DEFAULT, 'islas turcas y caicos'),
    (DEFAULT, 'islas virgenes britanicas'),
    (DEFAULT, 'islas virgenes de los estados unidos'),
    (DEFAULT, 'abjasia'),
    (DEFAULT, 'chipre del norte'),
    (DEFAULT, 'kosovo'),
    (DEFAULT, 'osetia del sur'),
    (DEFAULT, 'somalilandia'),
    (DEFAULT, 'taiwan');*/
